image: node:14.17.0

clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:
  services:
    docker:
      memory: 2048
  caches:
    sonar: ~/.sonar/cache # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - node
          - sonar
        script:
          - pipe: sonarsource/sonarcloud-scan:1.2.2
    - step: &check-quality-gate-sonarcloud
        name: Check the Quality Gate on SonarCloud
        script:
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.4

pipelines: # More info here: https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html
  default:
    - step:
        size: 2x # Double resources available for this step.
  branches:
    '**':
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
pull-requests:
  '**':
    - step: *build-test-sonarcloud
    - step: *check-quality-gate-sonarcloud
