
const AuthTypes = {
    SET_AUTH_DATA: 'SET_AUTH_DATA',
    
    LOADING_START: 'LOADING_START',
    LOADING_STOP: 'LOADING_STOP',

    SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

    SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
}

export default AuthTypes;
